/**
 * AI content marking.
 *
 * The EU AI Act splits disclosure into two duties, so this is two independent
 * switches rather than one setting:
 *
 * - the provider's duty to make synthetic content **machine-readable**, met by
 *   writing the IPTC/XMP `DigitalSourceType`;
 * - the deployer's duty to **disclose it to people**, met by compositing the
 *   European Commission's official AI-content label into the media.
 *
 * Both default to off, because both are the caller's decision to make.
 *
 * **On C2PA.** A manifest only carries provenance if it is signed, and signing
 * needs a certificate the user does not have. A test-signed manifest looks
 * like provenance while carrying none, which is worse than no manifest at all.
 * Nothing here writes one; the IPTC/XMP marker needs no certificate and is
 * what platforms actually read.
 *
 * **Provider metadata is never discarded.** If a file already declares a
 * digital source type, its metadata is left alone and that is reported. If it
 * carries other metadata without a source type, the marker is added to it
 * rather than replacing it.
 */

import { readFile, writeFile } from 'node:fs/promises'
import * as path from 'node:path'
import { ERROR_CODE, MediagenError } from '../core/errors.js'
import { mimeForExtension, sniffMediaType } from '../core/mediaType.js'
import { EU_ICONS, type EuIconKind } from './euIcons.js'
import {
  DEFAULT_POSITION,
  gravityFor,
  quietestCorner,
  regionFor,
  regionStats,
  type Corner,
  type LabelPosition,
} from './position.js'
import type sharpType from 'sharp'

/**
 * sharp is loaded dynamically, so its factory is passed around rather than
 * imported at module scope — a run that marks nothing should not pay to load
 * a native dependency.
 */
type SharpFactory = typeof sharpType

/** IPTC controlled-vocabulary term for content generated by a trained model. */
export const TRAINED_ALGORITHMIC_MEDIA =
  'http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia'

const IPTC_EXT_NAMESPACE = 'http://iptc.org/std/Iptc4xmpExt/2008-02-29/'
const XMP_NAMESPACE = 'http://ns.adobe.com/xap/1.0/'

/**
 * How much of the image's shorter side the label spans.
 *
 * The Commission asks for a "clearly visible size" without giving a number.
 * A fifth of the width is legible on a thumbnail and unobtrusive at 4K, and
 * scaling with the image means both hold.
 */
const LABEL_WIDTH_FRACTION = 0.2

/** Smallest the label may render at before it stops being readable. */
const MIN_LABEL_WIDTH = 96

/** Distance from the edge, as a fraction of the image's shorter side. */
const MARGIN_FRACTION = 0.025

/**
 * Formats this build can mark.
 *
 * Honesty here beats a promise: XMP in a video container is
 * a different operation from XMP in a still, and this build does not do it.
 * A video is refused by name instead of being silently left unmarked, which
 * would leave a caller believing a disclosure duty had been met.
 */
const MARKABLE_MIME_TYPES = new Set(['image/png', 'image/jpeg', 'image/webp'])

export interface MarkingOptions {
  /** Write the machine-readable IPTC/XMP marker. */
  readonly machineReadable: boolean
  /** Composite a visible disclosure into the media. */
  readonly visibleLabel: boolean
  /**
   * Which claim the visible label makes.
   *
   * The Commission separates content made entirely by a model from human
   * content a model altered, and so does the request: one supplied input
   * media and the other did not. Defaults to `generated`.
   */
  readonly labelKind?: EuIconKind
  /**
   * Which corner the visible label sits in, or `auto` to place it where the
   * image is calmest. Defaults to bottom-right.
   */
  readonly labelPosition?: LabelPosition
}

/** What produced the media, recorded alongside the marker. */
export interface MarkingProvenance {
  readonly provider?: string
  readonly model?: string
}

export interface MarkingResult {
  readonly filePath: string
  /** Where the visible label went, once `auto` has been resolved. */
  readonly labelPosition?: Corner
  /** True when this call wrote the machine-readable marker. */
  readonly machineReadableWritten: boolean
  /** True when the file already carried a digital source type. */
  readonly alreadyMarked: boolean
  /** True when a visible label was composited in. */
  readonly visibleLabelWritten: boolean
}

/** True when a packet already declares any digital source type. */
export function hasDigitalSourceType(xmp: string | undefined): boolean {
  return typeof xmp === 'string' && /DigitalSourceType/i.test(xmp)
}

export async function markFile(
  filePath: string,
  options: MarkingOptions,
  provenance: MarkingProvenance = {},
): Promise<MarkingResult> {
  if (!options.machineReadable && !options.visibleLabel) {
    return {
      filePath,
      machineReadableWritten: false,
      alreadyMarked: false,
      visibleLabelWritten: false,
    }
  }

  const original = await readFile(filePath).catch(() => {
    throw new MediagenError(ERROR_CODE.FILE_ERROR, `Cannot read ${filePath}.`, {
      hint: 'Check the path and that the file is readable.',
    })
  })

  requireMarkable(filePath, original)

  // Loaded here rather than at module scope: sharp is a native dependency and
  // a run that marks nothing should not pay to load it.
  const sharp = (await import('sharp')).default

  const existing = await sharp(original).metadata()
  const existingXmp = existing.xmp?.toString('utf-8')
  const alreadyMarked = hasDigitalSourceType(existingXmp)

  let pipeline = sharp(original).keepMetadata()
  let placedAt: Corner | undefined

  if (options.visibleLabel) {
    const width = existing.width ?? 1024
    const height = existing.height ?? 1024
    const requested = options.labelPosition ?? DEFAULT_POSITION

    placedAt =
      requested === 'auto' ? await quietestCorner(sharp, original, width, height) : requested

    const label = await buildLabel(
      sharp,
      original,
      width,
      height,
      options.labelKind ?? 'generated',
      placedAt,
    )
    pipeline = pipeline.composite([{ input: label, gravity: gravityFor(placedAt) }])
  }

  // A file that already declares a source type is left alone and reported.
  // Overwriting would discard whatever the provider recorded about itself.
  const machineReadableWritten = options.machineReadable && !alreadyMarked
  if (machineReadableWritten) {
    pipeline = pipeline.withXmp(
      existingXmp === undefined
        ? buildXmpPacket(provenance)
        : injectIntoXmp(existingXmp, provenance),
    )
  }

  const marked = await pipeline.toBuffer().catch((error: unknown) => {
    throw new MediagenError(ERROR_CODE.FILE_ERROR, `Could not mark ${path.basename(filePath)}.`, {
      hint: 'The file may be corrupt or in a format this build cannot rewrite.',
      cause: error,
    })
  })

  await writeFile(filePath, marked).catch(() => {
    throw new MediagenError(ERROR_CODE.FILE_ERROR, `Cannot write ${filePath}.`, {
      hint: 'Check that the file is not read-only.',
    })
  })

  return {
    filePath,
    machineReadableWritten,
    alreadyMarked,
    visibleLabelWritten: options.visibleLabel,
    ...(placedAt === undefined ? {} : { labelPosition: placedAt }),
  }
}

function requireMarkable(filePath: string, data: Uint8Array): void {
  const mimeType = sniffMediaType(data)?.mimeType ?? mimeForExtension(path.extname(filePath))

  if (mimeType !== undefined && MARKABLE_MIME_TYPES.has(mimeType)) return

  const described = mimeType ?? 'an unrecognised format'

  throw new MediagenError(
    ERROR_CODE.VALIDATION_ERROR,
    `This build cannot mark ${described}. It marks ${[...MARKABLE_MIME_TYPES].join(', ')}.`,
    {
      hint: described.startsWith('video/')
        ? 'Writing XMP into a video container is a different operation from writing it into a still, and is not implemented.'
        : 'Convert the file to PNG, JPEG or WebP first.',
    },
  )
}

/** Escapes text for inclusion in XML character data or an attribute value. */
function escapeXml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

function buildProperties(provenance: MarkingProvenance): string {
  const creatorTool = escapeXml([provenance.provider, provenance.model].filter(Boolean).join(' '))

  const lines = [
    `<Iptc4xmpExt:DigitalSourceType>${TRAINED_ALGORITHMIC_MEDIA}</Iptc4xmpExt:DigitalSourceType>`,
  ]
  if (creatorTool.length > 0) {
    lines.push(`<xmp:CreatorTool>${creatorTool}</xmp:CreatorTool>`)
  }
  return lines.join('')
}

/** A complete XMP packet, used when the file carries no XMP at all. */
function buildXmpPacket(provenance: MarkingProvenance): string {
  return [
    '<?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?>',
    '<x:xmpmeta xmlns:x="adobe:ns:meta/">',
    '<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">',
    '<rdf:Description rdf:about=""',
    ` xmlns:Iptc4xmpExt="${IPTC_EXT_NAMESPACE}"`,
    ` xmlns:xmp="${XMP_NAMESPACE}">`,
    buildProperties(provenance),
    '</rdf:Description>',
    '</rdf:RDF>',
    '</x:xmpmeta>',
    '<?xpacket end="w"?>',
  ].join('')
}

/**
 * Adds the marker to an existing packet rather than replacing it, so provider
 * metadata such as model identifiers survives.
 */
function injectIntoXmp(existing: string, provenance: MarkingProvenance): string {
  const descriptionMatch = /<rdf:Description\b[^>]*>/.exec(existing)
  if (!descriptionMatch) {
    // No element to extend; a fresh packet is the only option.
    return buildXmpPacket(provenance)
  }

  let openingTag = descriptionMatch[0]
  if (!openingTag.includes('xmlns:Iptc4xmpExt')) {
    openingTag = openingTag.replace(/>$/, ` xmlns:Iptc4xmpExt="${IPTC_EXT_NAMESPACE}">`)
  }
  if (!openingTag.includes('xmlns:xmp=')) {
    openingTag = openingTag.replace(/>$/, ` xmlns:xmp="${XMP_NAMESPACE}">`)
  }

  const insertAt = descriptionMatch.index + descriptionMatch[0].length
  return (
    existing.slice(0, descriptionMatch.index) +
    openingTag +
    buildProperties(provenance) +
    existing.slice(insertAt)
  )
}

/**
 * Renders the official label at a size that suits the image.
 *
 * Two choices are made here. The size scales with the image so the same call
 * produces something legible on a thumbnail and proportionate at 4K. And the
 * colour is chosen from the corner it will sit in: the Commission ships a
 * dark badge and a light one precisely because neither works everywhere, and
 * a label nobody can read is not a disclosure.
 */
async function buildLabel(
  sharp: SharpFactory,
  original: Uint8Array,
  width: number,
  height: number,
  kind: EuIconKind,
  corner: Corner,
): Promise<Buffer> {
  const shortest = Math.min(width, height)
  const margin = Math.round(shortest * MARGIN_FRACTION)

  // Never wider than the image itself, margins included: sharp refuses to
  // composite something larger than its canvas, which would turn a request
  // for a disclosure into an error.
  const available = Math.max(1, width - margin * 2)
  const labelWidth = Math.max(
    1,
    Math.min(available, Math.max(MIN_LABEL_WIDTH, Math.round(width * LABEL_WIDTH_FRACTION))),
  )

  const icon = EU_ICONS[kind]
  const variant = (await isDarkCorner(sharp, original, width, height, corner))
    ? icon.light
    : icon.dark
  const labelHeight = Math.max(1, Math.round(labelWidth / variant.aspectRatio))

  const rendered = await sharp(Buffer.from(variant.svg), { density: 600 })
    .resize(labelWidth, labelHeight, { fit: 'contain', background: TRANSPARENT })
    .png()
    .toBuffer()

  // Extended rather than positioned, so the margin travels with the label and
  // gravity still puts it where it belongs. The padding goes on the sides
  // facing the edges the label is pushed against.
  return await sharp(rendered)
    .extend({
      ...(corner.endsWith('right') ? { right: margin } : { left: margin }),
      ...(corner.startsWith('bottom') ? { bottom: margin } : { top: margin }),
      background: TRANSPARENT,
    })
    .png()
    .toBuffer()
}

const TRANSPARENT = { r: 0, g: 0, b: 0, alpha: 0 } as const

/**
 * Samples the corner the label will occupy.
 *
 * Only that corner, not the whole image: a photograph can be bright overall
 * and black exactly where the badge lands.
 */
async function isDarkCorner(
  sharp: SharpFactory,
  original: Uint8Array,
  width: number,
  height: number,
  corner: Corner,
): Promise<boolean> {
  const stats = await regionStats(sharp, original, regionFor(corner, width, height))

  // A format sharp can decode but not crop is not worth failing over; the
  // dark badge is the Commission's own default rendering.
  return stats === undefined ? false : stats.mean < 128
}
