/**
 * Generated from Kie AI's documentation. Do not edit by hand.
 *
 * Regenerate with:
 *   npm run sync:kie-models
 *
 * Source: https://docs.kie.ai/llms.txt and the OpenAPI specification embedded
 * in each model's documentation page. 37 image models, 36 video models.
 */

import type { KieModelShape, KieVideoModelShape } from './modelShape.js'

export const GENERATED_KIE_MODELS = {
  'bytedance/seedream': {
    textToImage: 'bytedance/seedream',
  },
  'bytedance/seedream-v4': {
    textToImage: 'bytedance/seedream-v4-text-to-image',
    imageToImage: 'bytedance/seedream-v4-edit',
    imageInputField: 'image_urls',
    imageInputIsArray: true,
  },
  'flux-2/flex': {
    textToImage: 'flux-2/flex-text-to-image',
    imageToImage: 'flux-2/flex-image-to-image',
    imageInputField: 'input_urls',
    imageInputIsArray: true,
    aspectRatios: ['1:1', '4:3', '3:4', '16:9', '9:16', '3:2', '2:3'],
    resolutions: ['1K', '2K'],
  },
  'flux-2/pro': {
    textToImage: 'flux-2/pro-text-to-image',
    imageToImage: 'flux-2/pro-image-to-image',
    imageInputField: 'input_urls',
    imageInputIsArray: true,
    aspectRatios: ['1:1', '4:3', '3:4', '16:9', '9:16', '3:2', '2:3'],
    resolutions: ['1K', '2K'],
  },
  'google/imagen4': {
    textToImage: 'google/imagen4',
    aspectRatios: ['1:1', '16:9', '9:16', '3:4', '4:3'],
  },
  'google/imagen4-fast': {
    textToImage: 'google/imagen4-fast',
    aspectRatios: ['1:1', '16:9', '9:16', '3:4', '4:3'],
  },
  'google/imagen4-ultra': {
    textToImage: 'google/imagen4-ultra',
    aspectRatios: ['1:1', '16:9', '9:16', '3:4', '4:3'],
  },
  'google/nano-banana': {
    textToImage: 'google/nano-banana',
    imageToImage: 'google/nano-banana-edit',
    imageInputField: 'image_urls',
    imageInputIsArray: true,
    aspectRatios: ['1:1', '9:16', '16:9', '3:4', '4:3', '3:2', '2:3', '5:4', '4:5', '21:9'],
    outputFormats: { png: 'png', jpeg: 'jpeg' },
  },
  'gpt-image-2': {
    textToImage: 'gpt-image-2-text-to-image',
    imageToImage: 'gpt-image-2-image-to-image',
    imageInputField: 'input_urls',
    imageInputIsArray: true,
    aspectRatios: ['1:1', '3:2', '2:3', '4:3', '3:4', '5:4', '4:5', '16:9', '9:16', '21:9'],
    resolutions: ['1K', '2K', '4K'],
  },
  'gpt-image-2-5-flare': {
    textToImage: 'gpt-image-2-5-flare-text-to-image',
    imageToImage: 'gpt-image-2-5-flare-image-to-image',
    imageInputField: 'input_urls',
    imageInputIsArray: true,
    aspectRatios: ['1:1', '3:2', '2:3', '4:3', '3:4', '16:9', '9:16', '21:9'],
    resolutions: ['1K', '2K', '4K'],
  },
  'gpt-image-2-5-sunburst': {
    textToImage: 'gpt-image-2-5-sunburst-text-to-image',
    imageToImage: 'gpt-image-2-5-sunburst-image-to-image',
    imageInputField: 'input_urls',
    imageInputIsArray: true,
    aspectRatios: ['1:1', '3:2', '2:3', '4:3', '3:4', '16:9', '9:16', '21:9'],
    resolutions: ['1K', '2K', '4K'],
  },
  'gpt-image/1.5': {
    textToImage: 'gpt-image/1.5-text-to-image',
    imageToImage: 'gpt-image/1.5-image-to-image',
    imageInputField: 'input_urls',
    imageInputIsArray: true,
    aspectRatios: ['1:1', '2:3', '3:2'],
  },
  'grok-imagine': {
    textToImage: 'grok-imagine/text-to-image',
    imageToImage: 'grok-imagine/image-to-image',
    imageInputField: 'image_urls',
    imageInputIsArray: true,
    aspectRatios: ['2:3', '3:2', '1:1', '16:9', '9:16'],
  },
  'grok-imagine-image-2-0': {
    textToImage: 'grok-imagine-image-2-0/text-to-image',
    aspectRatios: ['1:1', '2:3', '3:2', '16:9', '9:16'],
  },
  'grok-imagine-image-2-0/image-edit': {
    imageToImage: 'grok-imagine-image-2-0/image-edit',
    imageInputField: 'image_urls',
    imageInputIsArray: true,
    aspectRatios: ['1:1', '2:3', '3:2', '16:9', '9:16'],
  },
  'ideogram/character': {
    textToImage: 'ideogram/character',
    imageToImage: 'ideogram/character-edit',
    imageInputField: 'image_url',
    imageInputIsArray: false,
  },
  'ideogram/character-remix': {
    textToImage: 'ideogram/character-remix',
    imageToImage: 'ideogram/character-remix',
    imageInputField: 'image_url',
    imageInputIsArray: false,
  },
  'ideogram/v3': {
    textToImage: 'ideogram/v3-text-to-image',
    imageToImage: 'ideogram/v3-edit',
    imageInputField: 'image_url',
    imageInputIsArray: false,
  },
  'ideogram/v3-remix': {
    textToImage: 'ideogram/v3-remix',
    imageToImage: 'ideogram/v3-remix',
    imageInputField: 'image_url',
    imageInputIsArray: false,
  },
  'nano-banana-2': {
    textToImage: 'nano-banana-2',
    imageToImage: 'nano-banana-2',
    imageInputField: 'image_input',
    imageInputIsArray: true,
    aspectRatios: ['1:1', '2:3', '3:2', '1:4', '4:1', '3:4', '4:3', '4:5', '5:4', '1:8', '8:1', '9:16', '16:9', '21:9'],
    resolutions: ['1K', '2K', '4K'],
    outputFormats: { png: 'png', jpeg: 'jpg' },
  },
  'nano-banana-2-lite': {
    textToImage: 'nano-banana-2-lite',
    imageToImage: 'nano-banana-2-lite',
    imageInputField: 'image_urls',
    imageInputIsArray: true,
    aspectRatios: ['1:1', '1:4', '1:8', '2:3', '3:2', '3:4', '4:1', '4:3', '4:5', '5:4', '8:1', '9:16', '16:9', '21:9'],
  },
  'nano-banana-pro': {
    textToImage: 'nano-banana-pro',
    imageToImage: 'nano-banana-pro',
    imageInputField: 'image_input',
    imageInputIsArray: true,
    aspectRatios: ['1:1', '2:3', '3:2', '3:4', '4:3', '4:5', '5:4', '9:16', '16:9', '21:9'],
    resolutions: ['1K', '2K', '4K'],
    outputFormats: { png: 'png', jpeg: 'jpg' },
  },
  'qwen': {
    textToImage: 'qwen/text-to-image',
    imageToImage: 'qwen/image-to-image',
    imageInputField: 'image_url',
    imageInputIsArray: false,
    outputFormats: { png: 'png', jpeg: 'jpeg' },
  },
  'qwen/image-edit': {
    imageToImage: 'qwen/image-edit',
    imageInputField: 'image_url',
    imageInputIsArray: false,
    outputFormats: { jpeg: 'jpeg', png: 'png' },
  },
  'qwen2-1': {
    textToImage: 'qwen2-1/text-to-image',
    imageToImage: 'qwen2-1/image-to-image',
    imageInputField: 'image_urls',
    imageInputIsArray: true,
    aspectRatios: ['1:1', '4:3', '3:4', '3:2', '2:3', '16:9', '9:16', '21:9'],
    resolutions: ['1K', '2K'],
    outputFormats: { png: 'png', jpeg: 'jpeg' },
  },
  'qwen2/image-edit': {
    imageToImage: 'qwen2/image-edit',
    imageInputField: 'image_url',
    imageInputIsArray: false,
    outputFormats: { jpeg: 'jpeg', png: 'png' },
  },
  'qwen3': {
    textToImage: 'qwen3/text-to-image',
    imageToImage: 'qwen3/image-to-image',
    imageInputField: 'image_urls',
    imageInputIsArray: true,
    resolutions: ['1K', '2K'],
    outputFormats: { png: 'png', jpeg: 'jpeg' },
  },
  'qwen3/pro': {
    textToImage: 'qwen3/pro-text-to-image',
    imageToImage: 'qwen3/pro-image-to-image',
    imageInputField: 'image_urls',
    imageInputIsArray: true,
    resolutions: ['1K', '2K'],
    outputFormats: { png: 'png', jpeg: 'jpeg' },
  },
  'seedream/4.5': {
    textToImage: 'seedream/4.5-text-to-image',
    imageToImage: 'seedream/4.5-edit',
    imageInputField: 'image_urls',
    imageInputIsArray: true,
    aspectRatios: ['1:1', '4:3', '3:4', '16:9', '9:16', '2:3', '3:2', '21:9'],
  },
  'seedream/5-flash': {
    textToImage: 'seedream/5-flash-text-to-image',
    imageToImage: 'seedream/5-flash-image-to-image',
    imageInputField: 'image_urls',
    imageInputIsArray: true,
    aspectRatios: ['1:1', '4:3', '3:4', '16:9', '9:16', '2:3', '3:2', '21:9'],
    outputFormats: { png: 'png', jpeg: 'jpeg' },
  },
  'seedream/5-flash-layer-decomposition': {
    textToImage: 'seedream/5-flash-layer-decomposition',
    imageToImage: 'seedream/5-flash-layer-decomposition',
    imageInputField: 'image_url',
    imageInputIsArray: false,
    outputFormats: { png: 'png', jpeg: 'jpeg' },
  },
  'seedream/5-lite': {
    textToImage: 'seedream/5-lite-text-to-image',
    imageToImage: 'seedream/5-lite-image-to-image',
    imageInputField: 'image_urls',
    imageInputIsArray: true,
    aspectRatios: ['1:1', '4:3', '3:4', '16:9', '9:16', '2:3', '3:2', '21:9'],
    outputFormats: { png: 'png', jpeg: 'jpeg' },
  },
  'seedream/5-pro': {
    textToImage: 'seedream/5-pro-text-to-image',
    imageToImage: 'seedream/5-pro-image-to-image',
    imageInputField: 'image_urls',
    imageInputIsArray: true,
    aspectRatios: ['1:1', '4:3', '3:4', '16:9', '9:16', '2:3', '3:2', '21:9'],
    outputFormats: { png: 'png', jpeg: 'jpeg' },
  },
  'seedream/5-pro-layer-decomposition': {
    textToImage: 'seedream/5-pro-layer-decomposition',
    imageToImage: 'seedream/5-pro-layer-decomposition',
    imageInputField: 'image_url',
    imageInputIsArray: false,
    outputFormats: { png: 'png', jpeg: 'jpeg' },
  },
  'wan/2-7-image': {
    textToImage: 'wan/2-7-image',
    imageToImage: 'wan/2-7-image',
    imageInputField: 'input_urls',
    imageInputIsArray: true,
    aspectRatios: ['1:1', '16:9', '4:3', '21:9', '3:4', '9:16', '8:1', '1:8'],
    resolutions: ['1K', '2K', '4K'],
  },
  'wan/2-7-image-pro': {
    textToImage: 'wan/2-7-image-pro',
    imageToImage: 'wan/2-7-image-pro',
    imageInputField: 'input_urls',
    imageInputIsArray: true,
    aspectRatios: ['1:1', '16:9', '4:3', '21:9', '3:4', '9:16', '8:1', '1:8'],
    resolutions: ['1K', '2K', '4K'],
  },
  'z-image': {
    textToImage: 'z-image',
    aspectRatios: ['1:1', '4:3', '3:4', '16:9', '9:16'],
  },
} as const satisfies Record<string, KieModelShape>

export const GENERATED_KIE_VIDEO_MODELS = {
  'bytedance/seedance-2': {
    textToVideo: {
      model: 'bytedance/seedance-2',
      aspectRatioField: 'aspect_ratio',
      aspectRatios: ['1:1', '4:3', '3:4', '16:9', '9:16', '21:9', 'adaptive'],
      resolutionField: 'resolution',
      resolutions: ['480p', '720p', '1080p', '4k'],
      durationType: 'number',
    },
    imageToVideo: {
      model: 'bytedance/seedance-2',
      imageInputField: 'first_frame_url',
      imageInputIsArray: false,
      aspectRatioField: 'aspect_ratio',
      aspectRatios: ['1:1', '4:3', '3:4', '16:9', '9:16', '21:9', 'adaptive'],
      resolutionField: 'resolution',
      resolutions: ['480p', '720p', '1080p', '4k'],
      durationType: 'number',
    },
  },
  'bytedance/seedance-2-5': {
    textToVideo: {
      model: 'bytedance/seedance-2-5',
      aspectRatioField: 'aspect_ratio',
      aspectRatios: ['1:1', '4:3', '3:4', '16:9', '9:16', '21:9', 'adaptive'],
      resolutionField: 'resolution',
      resolutions: ['480p', '720p', '1080p'],
      durationType: 'number',
    },
    imageToVideo: {
      model: 'bytedance/seedance-2-5',
      imageInputField: 'first_frame_url',
      imageInputIsArray: false,
      aspectRatioField: 'aspect_ratio',
      aspectRatios: ['1:1', '4:3', '3:4', '16:9', '9:16', '21:9', 'adaptive'],
      resolutionField: 'resolution',
      resolutions: ['480p', '720p', '1080p'],
      durationType: 'number',
    },
  },
  'bytedance/seedance-2-fast': {
    textToVideo: {
      model: 'bytedance/seedance-2-fast',
      aspectRatioField: 'aspect_ratio',
      aspectRatios: ['1:1', '4:3', '3:4', '16:9', '9:16', '21:9', 'adaptive'],
      resolutionField: 'resolution',
      resolutions: ['480p', '720p'],
      durationType: 'number',
    },
    imageToVideo: {
      model: 'bytedance/seedance-2-fast',
      imageInputField: 'first_frame_url',
      imageInputIsArray: false,
      aspectRatioField: 'aspect_ratio',
      aspectRatios: ['1:1', '4:3', '3:4', '16:9', '9:16', '21:9', 'adaptive'],
      resolutionField: 'resolution',
      resolutions: ['480p', '720p'],
      durationType: 'number',
    },
  },
  'bytedance/seedance-2-mini': {
    textToVideo: {
      model: 'bytedance/seedance-2-mini',
      aspectRatioField: 'aspect_ratio',
      aspectRatios: ['1:1', '4:3', '3:4', '16:9', '9:16', '21:9', 'adaptive'],
      resolutionField: 'resolution',
      resolutions: ['480p', '720p'],
      durationType: 'number',
    },
    imageToVideo: {
      model: 'bytedance/seedance-2-mini',
      imageInputField: 'first_frame_url',
      imageInputIsArray: false,
      aspectRatioField: 'aspect_ratio',
      aspectRatios: ['1:1', '4:3', '3:4', '16:9', '9:16', '21:9', 'adaptive'],
      resolutionField: 'resolution',
      resolutions: ['480p', '720p'],
      durationType: 'number',
    },
  },
  'bytedance/v1-lite': {
    textToVideo: {
      model: 'bytedance/v1-lite-text-to-video',
      aspectRatioField: 'aspect_ratio',
      aspectRatios: ['16:9', '4:3', '1:1', '3:4', '9:16', '9:21'],
      resolutionField: 'resolution',
      resolutions: ['480p', '720p', '1080p'],
      durationType: 'string',
      durations: [5, 10],
    },
    imageToVideo: {
      model: 'bytedance/v1-lite-image-to-video',
      imageInputField: 'image_url',
      imageInputIsArray: false,
      resolutionField: 'resolution',
      resolutions: ['480p', '720p', '1080p'],
      durationType: 'string',
      durations: [5, 10],
    },
  },
  'bytedance/v1-pro': {
    textToVideo: {
      model: 'bytedance/v1-pro-text-to-video',
      aspectRatioField: 'aspect_ratio',
      aspectRatios: ['21:9', '16:9', '4:3', '1:1', '3:4', '9:16'],
      resolutionField: 'resolution',
      resolutions: ['480p', '720p', '1080p'],
      durationType: 'string',
      durations: [5, 10],
    },
    imageToVideo: {
      model: 'bytedance/v1-pro-image-to-video',
      imageInputField: 'image_url',
      imageInputIsArray: false,
      resolutionField: 'resolution',
      resolutions: ['480p', '720p', '1080p'],
      durationType: 'string',
      durations: [5, 10],
    },
  },
  'bytedance/v1-pro-fast-image-to-video': {
    imageToVideo: {
      model: 'bytedance/v1-pro-fast-image-to-video',
      imageInputField: 'image_url',
      imageInputIsArray: false,
      resolutionField: 'resolution',
      resolutions: ['720p', '1080p'],
      durationType: 'string',
      durations: [5, 10],
    },
  },
  'gemini-omni-video': {
    textToVideo: {
      model: 'gemini-omni-video',
      aspectRatioField: 'aspect_ratio',
      aspectRatios: ['16:9', '9:16'],
      resolutionField: 'resolution',
      resolutions: ['720p', '1080p', '4k'],
      durationType: 'string',
      durations: [4, 6, 8, 10],
      defaults: { duration: '4' },
    },
    imageToVideo: {
      model: 'gemini-omni-video',
      imageInputField: 'image_urls',
      imageInputIsArray: true,
      aspectRatioField: 'aspect_ratio',
      aspectRatios: ['16:9', '9:16'],
      resolutionField: 'resolution',
      resolutions: ['720p', '1080p', '4k'],
      durationType: 'string',
      durations: [4, 6, 8, 10],
      defaults: { duration: '4' },
    },
  },
  'google/gemini-omni-flash-1-1': {
    textToVideo: {
      model: 'google/gemini-omni-flash-1-1',
      aspectRatioField: 'aspect_ratio',
      aspectRatios: ['16:9', '9:16'],
      resolutionField: 'resolution',
      resolutions: ['360p', '720p', '1080p', '4k'],
      durationType: 'string',
      durations: [4, 6, 8, 10],
      defaults: { duration: '4' },
    },
    imageToVideo: {
      model: 'google/gemini-omni-flash-1-1',
      imageInputField: 'first_frame_url',
      imageInputIsArray: false,
      aspectRatioField: 'aspect_ratio',
      aspectRatios: ['16:9', '9:16'],
      resolutionField: 'resolution',
      resolutions: ['360p', '720p', '1080p', '4k'],
      durationType: 'string',
      durations: [4, 6, 8, 10],
      defaults: { duration: '4' },
    },
  },
  'grok-imagine': {
    textToVideo: {
      model: 'grok-imagine/text-to-video',
      aspectRatioField: 'aspect_ratio',
      aspectRatios: ['2:3', '3:2', '1:1', '16:9', '9:16'],
      resolutionField: 'resolution',
      resolutions: ['480p', '720p', '1080p'],
      durationType: 'number',
    },
    imageToVideo: {
      model: 'grok-imagine/image-to-video',
      imageInputField: 'image_urls',
      imageInputIsArray: true,
      aspectRatioField: 'aspect_ratio',
      aspectRatios: ['2:3', '3:2', '1:1', '16:9', '9:16'],
      resolutionField: 'resolution',
      resolutions: ['480p', '720p', '1080p'],
      durationType: 'string',
    },
  },
  'grok-imagine-video-1-5-preview': {
    textToVideo: {
      model: 'grok-imagine-video-1-5-preview',
      aspectRatioField: 'aspect_ratio',
      aspectRatios: ['1:1', '16:9', '9:16', '3:2', '2:3', 'auto'],
      resolutionField: 'resolution',
      resolutions: ['480p', '720p', '1080p'],
      durationType: 'number',
      durations: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    },
    imageToVideo: {
      model: 'grok-imagine-video-1-5-preview',
      imageInputField: 'image_urls',
      imageInputIsArray: true,
      aspectRatioField: 'aspect_ratio',
      aspectRatios: ['1:1', '16:9', '9:16', '3:2', '2:3', 'auto'],
      resolutionField: 'resolution',
      resolutions: ['480p', '720p', '1080p'],
      durationType: 'number',
      durations: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    },
  },
  'hailuo/02-image-to-video-pro': {
    imageToVideo: {
      model: 'hailuo/02-image-to-video-pro',
      imageInputField: 'image_url',
      imageInputIsArray: false,
    },
  },
  'hailuo/02-image-to-video-standard': {
    imageToVideo: {
      model: 'hailuo/02-image-to-video-standard',
      imageInputField: 'image_url',
      imageInputIsArray: false,
      resolutionField: 'resolution',
      resolutions: ['512P', '768P'],
      durationType: 'string',
      durations: [6, 10],
    },
  },
  'hailuo/02-text-to-video-pro': {
    textToVideo: {
      model: 'hailuo/02-text-to-video-pro',
    },
  },
  'hailuo/02-text-to-video-standard': {
    textToVideo: {
      model: 'hailuo/02-text-to-video-standard',
      durationType: 'string',
      durations: [6, 10],
    },
  },
  'hailuo/2-3-image-to-video-pro': {
    imageToVideo: {
      model: 'hailuo/2-3-image-to-video-pro',
      imageInputField: 'image_url',
      imageInputIsArray: false,
      resolutionField: 'resolution',
      resolutions: ['768P', '1080P'],
      durationType: 'string',
      durations: [6, 10],
    },
  },
  'hailuo/2-3-image-to-video-standard': {
    imageToVideo: {
      model: 'hailuo/2-3-image-to-video-standard',
      imageInputField: 'image_url',
      imageInputIsArray: false,
      resolutionField: 'resolution',
      resolutions: ['768P', '1080P'],
      durationType: 'string',
      durations: [6, 10],
    },
  },
  'happyhorse': {
    textToVideo: {
      model: 'happyhorse/text-to-video',
      aspectRatioField: 'aspect_ratio',
      aspectRatios: ['16:9', '9:16', '1:1', '4:3', '3:4'],
      resolutionField: 'resolution',
      resolutions: ['720p', '1080p'],
      durationType: 'number',
      durations: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    },
    imageToVideo: {
      model: 'happyhorse/image-to-video',
      imageInputField: 'image_urls',
      imageInputIsArray: true,
      resolutionField: 'resolution',
      resolutions: ['720p', '1080p'],
      durationType: 'number',
      durations: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    },
  },
  'happyhorse-1-1': {
    textToVideo: {
      model: 'happyhorse-1-1/text-to-video',
      aspectRatioField: 'aspect_ratio',
      aspectRatios: ['16:9', '9:16', '1:1', '4:3', '3:4', '4:5', '5:4', '9:21', '21:9'],
      resolutionField: 'resolution',
      resolutions: ['720p', '1080p'],
      durationType: 'number',
      durations: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    },
    imageToVideo: {
      model: 'happyhorse-1-1/image-to-video',
      imageInputField: 'image_urls',
      imageInputIsArray: true,
      resolutionField: 'resolution',
      resolutions: ['720p', '1080p'],
      durationType: 'number',
      durations: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    },
  },
  'kling-2.6': {
    textToVideo: {
      model: 'kling-2.6/text-to-video',
      aspectRatioField: 'aspect_ratio',
      aspectRatios: ['1:1', '16:9', '9:16'],
      durationType: 'string',
      durations: [5, 10],
      defaults: { sound: false, aspect_ratio: '1:1', duration: '5' },
    },
    imageToVideo: {
      model: 'kling-2.6/image-to-video',
      imageInputField: 'image_urls',
      imageInputIsArray: true,
      durationType: 'string',
      durations: [5, 10],
      defaults: { sound: false, duration: '5' },
    },
  },
  'kling-3.0-omni': {
    textToVideo: {
      model: 'kling-3.0-omni/text-to-video',
      aspectRatioField: 'aspect_ratio',
      aspectRatios: ['16:9', '9:16', '1:1'],
      resolutionField: 'resolution',
      resolutions: ['720p', '1080p', '4k'],
      durationType: 'number',
      durations: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    },
  },
  'kling/v2-1-master': {
    textToVideo: {
      model: 'kling/v2-1-master-text-to-video',
      aspectRatioField: 'aspect_ratio',
      aspectRatios: ['16:9', '9:16', '1:1'],
      durationType: 'string',
      durations: [5, 10],
    },
    imageToVideo: {
      model: 'kling/v2-1-master-image-to-video',
      imageInputField: 'image_url',
      imageInputIsArray: false,
      durationType: 'string',
      durations: [5, 10],
    },
  },
  'kling/v2-1-pro': {
    imageToVideo: {
      model: 'kling/v2-1-pro',
      imageInputField: 'image_url',
      imageInputIsArray: false,
      durationType: 'string',
      durations: [5, 10],
    },
  },
  'kling/v2-1-standard': {
    imageToVideo: {
      model: 'kling/v2-1-standard',
      imageInputField: 'image_url',
      imageInputIsArray: false,
      durationType: 'string',
      durations: [5, 10],
    },
  },
  'kling/v2-5-turbo-text-to-video-pro': {
    textToVideo: {
      model: 'kling/v2-5-turbo-text-to-video-pro',
      aspectRatioField: 'aspect_ratio',
      aspectRatios: ['16:9', '9:16', '1:1'],
      durationType: 'string',
      durations: [5, 10],
    },
  },
  'kling/v3-turbo': {
    textToVideo: {
      model: 'kling/v3-turbo-text-to-video',
      aspectRatioField: 'aspect_ratio',
      aspectRatios: ['1:1', '9:16', '16:9'],
      resolutionField: 'resolution',
      resolutions: ['720p', '1080p'],
      durationType: 'string',
      defaults: { duration: '5', aspect_ratio: '16:9', resolution: '720p' },
    },
    imageToVideo: {
      model: 'kling/v3-turbo-image-to-video',
      imageInputField: 'image_urls',
      imageInputIsArray: true,
      resolutionField: 'resolution',
      resolutions: ['720p', '1080p'],
      durationType: 'string',
      defaults: { duration: '5', resolution: '720p' },
    },
  },
  'minimax-h3': {
    textToVideo: {
      model: 'minimax-h3/text-to-video',
      aspectRatioField: 'aspect_ratio',
      aspectRatios: ['21:9', '16:9', '4:3', '1:1', '3:4', '9:16'],
      resolutionField: 'resolution',
      resolutions: ['768P', '2K'],
      durationType: 'number',
      durations: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
      defaults: { aspect_ratio: '16:9', duration: 6 },
    },
    imageToVideo: {
      model: 'minimax-h3/image-to-video',
      imageInputField: 'first_frame_url',
      imageInputIsArray: false,
      resolutionField: 'resolution',
      resolutions: ['768P', '2K'],
      durationType: 'number',
      durations: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
      defaults: { duration: 6 },
    },
  },
  'pixverse-v6': {
    textToVideo: {
      model: 'pixverse-v6/text-to-video',
      aspectRatioField: 'aspect_ratio',
      aspectRatios: ['16:9', '4:3', '1:1', '3:4', '9:16', '2:3', '3:2', '21:9'],
      resolutionField: 'quality',
      resolutions: ['360p', '540p', '720p', '1080p'],
      durationType: 'number',
      durations: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
      defaults: { aspect_ratio: '16:9', quality: '720p', duration: 5 },
    },
    imageToVideo: {
      model: 'pixverse-v6/image-to-video',
      imageInputField: 'image_urls',
      imageInputIsArray: true,
      resolutionField: 'quality',
      resolutions: ['360p', '540p', '720p', '1080p'],
      durationType: 'number',
      durations: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
      defaults: { quality: '720p', duration: 5 },
    },
  },
  'wan/2-2-a14b-image-to-video-turbo': {
    imageToVideo: {
      model: 'wan/2-2-a14b-image-to-video-turbo',
      imageInputField: 'image_url',
      imageInputIsArray: false,
      resolutionField: 'resolution',
      resolutions: ['480p', '720p'],
    },
  },
  'wan/2-2-a14b-text-to-video-turbo': {
    textToVideo: {
      model: 'wan/2-2-a14b-text-to-video-turbo',
      aspectRatioField: 'aspect_ratio',
      aspectRatios: ['16:9', '9:16'],
      resolutionField: 'resolution',
      resolutions: ['480p', '720p'],
    },
  },
  'wan/2-5': {
    textToVideo: {
      model: 'wan/2-5-text-to-video',
      aspectRatioField: 'aspect_ratio',
      aspectRatios: ['16:9', '9:16', '1:1'],
      resolutionField: 'resolution',
      resolutions: ['720p', '1080p'],
      durationType: 'string',
      durations: [5, 10],
      defaults: { duration: '5' },
    },
    imageToVideo: {
      model: 'wan/2-5-image-to-video',
      imageInputField: 'image_url',
      imageInputIsArray: false,
      resolutionField: 'resolution',
      resolutions: ['720p', '1080p'],
      durationType: 'string',
      durations: [5, 10],
      defaults: { duration: '5' },
    },
  },
  'wan/2-6': {
    textToVideo: {
      model: 'wan/2-6-text-to-video',
      resolutionField: 'resolution',
      resolutions: ['720p', '1080p'],
      durationType: 'string',
      durations: [5, 10, 15],
    },
    imageToVideo: {
      model: 'wan/2-6-image-to-video',
      imageInputField: 'image_urls',
      imageInputIsArray: true,
      resolutionField: 'resolution',
      resolutions: ['720p', '1080p'],
      durationType: 'string',
      durations: [5, 10, 15],
    },
  },
  'wan/2-6-flash-image-to-video': {
    imageToVideo: {
      model: 'wan/2-6-flash-image-to-video',
      imageInputField: 'image_urls',
      imageInputIsArray: true,
      resolutionField: 'resolution',
      resolutions: ['720p', '1080p'],
      durationType: 'string',
      durations: [5, 10, 15],
      defaults: { audio: false },
    },
  },
  'wan/2-7': {
    textToVideo: {
      model: 'wan/2-7-text-to-video',
      aspectRatioField: 'ratio',
      aspectRatios: ['16:9', '9:16', '1:1', '4:3', '3:4'],
      resolutionField: 'resolution',
      resolutions: ['720p', '1080p'],
      durationType: 'number',
      durations: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    },
    imageToVideo: {
      model: 'wan/2-7-image-to-video',
      imageInputField: 'first_frame_url',
      imageInputIsArray: false,
      resolutionField: 'resolution',
      resolutions: ['720p', '1080p'],
      durationType: 'number',
      durations: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    },
  },
  'wan/3-0-video': {
    textToVideo: {
      model: 'wan/3-0-video',
      aspectRatioField: 'aspect_ratio',
      aspectRatios: ['adaptive', '16:9', '4:3', '1:1', '3:4', '9:16'],
      resolutionField: 'resolution',
      resolutions: ['480P', '720P', '1080P'],
      durationType: 'number',
    },
  },
  'wan/3-0-video-prime': {
    textToVideo: {
      model: 'wan/3-0-video-prime',
      aspectRatioField: 'aspect_ratio',
      aspectRatios: ['adaptive', '16:9', '4:3', '1:1', '3:4', '9:16'],
      resolutionField: 'resolution',
      resolutions: ['480P', '720P', '1080P'],
      durationType: 'number',
    },
  },
} as const satisfies Record<string, KieVideoModelShape>
